---
title: "Exploração de dados"
author: "Juan Belieni"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../")

library(tidyverse)
```

Nesta exploração de dados, vou buscar entender como cada variável se comporta e como elas se relacionam entre si.

## Exploração inicial

### Variáveis

```{r}
data <- read_csv("./data/indicadores-2012.csv") %>%
  filter(modalidade_ensino == 1 & ano_integralizacao == ano_referencia) %>%
  mutate(
    administracao = as.factor(administracao),
    tipo_administracao = as.factor(case_when(
      administracao %in% c(1, 2, 3) ~ "Pública",
      administracao %in% c(4, 5) ~ "Privada",
      administracao == 7 ~ "Especial"
    )),
    org_academica = as.factor(org_academica),
    cod_curso = as.factor(cod_curso),
    cod_regiao = as.factor(case_when(
      cod_regiao == 1 ~ "Norte",
      cod_regiao == 2 ~ "Nordeste",
      cod_regiao == 3 ~ "Sudeste",
      cod_regiao == 4 ~ "Sul",
      cod_regiao == 5 ~ "Centro-Oeste",
      TRUE ~ "Outro"
    )),
    cod_area = as.factor(cod_area),
    modalidade_ensino = as.factor(modalidade_ensino),
    grau_academico = as.factor(grau_academico),
    razao_evasao = qt_desistencias / qt_ingressantes,
  )
```

```{r}
data %>% names()
```


```{r}
data %>% glimpse()
```

## Gráficos

```{r}
data %>%
  group_by(cod_ies, administracao, tipo_administracao) %>%
  summarise(n = n()) %>%
  ggplot(aes(x = as.factor(administracao), fill = tipo_administracao)) +
  geom_bar() +
  labs(
    x = "Código da categoria administrativa",
    y = "Número de instituições",
    title = "Número de instituições por categoria administrativa",
    fill = "Tipo de administração"
  )
```

Onde a descrição de cada código é:

1. Pública Federal
2. Pública Estadual
3. Pública Municipal
4. Privada com fins
lucrativos
5. Privada sem fins
lucrativos
7. Especial

```{r}
data %>%
  group_by(administracao, tipo_administracao) %>%
  summarise(n = sum(qt_ingressantes)) %>%
  ggplot(aes(x = as.factor(administracao), y = n, fill = tipo_administracao)) +
  geom_col() +
  labs(
    x = "Código da categoria administrativa",
    y = "Número de alunos",
    title = "Número de alunos por categoria administrativa",
    fill = "Tipo de administração"
  )
```

```{r}
data %>%
  group_by(regiao) %>%
  summarise(n = sum(qt_ingressantes)) %>%
  ggplot(aes(x = regiao, y = n)) +
  geom_col() +
  labs(
    x = "Região",
    y = "Número de alunos",
    title = "Número de alunos por região"
  )
```

```{r}
# plot prazo_integralizacao vs qt_desistencias
data %>%
  ggplot(aes(x = prazo_integralizacao, y = qt_desistencias)) +
  geom_point() +
  # regreção polinomial de grau 2
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  labs(
    x = "Prazo de integralização",
    y = "Número de desistentes",
    title = "Número de desistentes por prazo de integralização"
  )
```

```{r}
```

## Exploração da evasão

### Gráficos

```{r}
data %>%
  group_by(regiao) %>%
  summarise(
    ingressantes = sum(qt_ingressantes),
    desistentes = sum(qt_desistencias)
  ) %>%
  gather(key = "tipo", value = "n", ingressantes, desistentes) %>%
  ggplot(aes(x = regiao, y = n, fill = tipo)) +
  geom_col(position = "dodge") +
  labs(
    x = "Região",
    y = "Número de alunos",
    title = "Número de alunos por região",
    fill = "Tipo"
  )
```

```{r}
data %>%
  ggplot(aes(x = qt_desistencias)) +
  geom_histogram(bins = 50) +
  labs(
    x = "Número de desistentes",
    y = "Frequência",
    title = "Histograma do número de desistentes"
  )
```

```{r}
data %>%
  ggplot(aes(x = qt_ingressantes)) +
  geom_histogram(bins = 50) +
  labs(
    x = "Número de ingressantes",
    y = "Frequência",
    title = "Histograma do número de ingressantes"
  )
```

```{r}
data %>%
  group_by(regiao, tipo_administracao) %>%
  summarise(
    evasao = sum(qt_desistencias) / sum(qt_ingressantes)
  ) %>%
  ggplot(aes(x = regiao, y = evasao, fill = tipo_administracao)) +
  geom_col(position = "dodge") +
  labs(
    x = "Região",
    y = "Taxa de evasão",
    title = "Taxa de evasão por região",
    fill = "Tipo de administração"
  )
```

```{r}
data %>%
  group_by(nome_area) %>%
  summarise(
    evasao = sum(qt_desistencias) / sum(qt_ingressantes)
  ) %>%
  ggplot(aes(
    x = evasao,
    y = reorder(nome_area, evasao)
  )) +
  geom_col() +
  labs(
    x = "Taxa de evasão",
    y = "Grande área de conhecimento",
    title = "Taxa de evasão por grande área de conhecimento",
  ) +
  guides(fill = FALSE) +
  scale_x_continuous(labels = scales::percent) +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 30))
```

```{r}
data %>%
  group_by(cod_ies) %>%
  summarise(
    qt_ingressantes = mean(qt_ingressantes),
    qt_desistencias = mean(qt_desistencias),
    tipo_administracao = unique(tipo_administracao)
  ) %>%
  ggplot(aes(
    x = qt_ingressantes,
    y = qt_desistencias,
    color = tipo_administracao,
  )) +
  geom_point() +
  labs(
    x = "Número de ingressantes",
    y = "Número de desistências",
    title = "Média de ingressantes e desistências por administação",
    color = "Tipo de administração"
  )
```

```{r}
data %>%
  mutate(razao_evasao = qt_desistencias / qt_ingressantes) %>%
  ggplot(aes(x = razao_evasao)) +
  geom_histogram(bins = 100) +
  labs(
    x = "Razão de desistências por ingressantes",
    y = "Frequência",
    title = "Histograma da razão de desistências por ingressantes"
  )
```

```{r}
data %>%
  filter(qt_desistencias > 0) %>%
  mutate(razao_evasao = qt_desistencias / qt_ingressantes) %>%
  sample_n(10000) %>%
  ggplot(aes(x = as.factor(administracao), y = razao_evasao)) +
  geom_boxplot() +
  labs(
    x = "Administração",
    y = "Razão de desistências por ingressantes",
    title = "Boxplot da razão de desistências por ingressantes por prazo de integralização"
  )
```

```{r}
data %>%
  filter(modalidade_ensino == 1) %>%
  ggplot(aes(x = qt_desistencias)) +
  geom_histogram(bins = 100) +
  labs(
    x = "Quantidade de desistências",
    y = "Frequência",
    title = "Histograma da quantidade de desistências por ingressantes"
  )
```
